on:
  push:
    branches:
    - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
    - develop
  workflow_dispatch:
name: Build and Test Code
jobs:
  build-artifacts:
    name: Build and Test Java Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.0.2
      with:
        token: ${{ github.token }}
        submodules: recursive
        fetch-depth: 0
    # -------------------------
    # Java JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.3.0
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Initialize CodeQL
      if: github.event_name == 'push'
      uses: github/codeql-action/init@b2c19fb9a2a485599ccf4ed5d65527d94bc57226 # v2.1.11
      with:
        languages: java
    # -------------------------
    # Maven Build
    - name: Build and run tests (develop)
      id: maven-build-develop
      if: ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop') || (github.event_name == 'pull_request' && github.base_ref == 'develop')
      run: |
        mvn -Preporting verify
    - name: Build and run tests (main)
      if: steps.maven-build-develop.conclusion == 'skipped'
      run: |
        mvn -Prelease -Preporting verify
    - name: Perform CodeQL Analysis
      if: github.event_name == 'push'
      uses: github/codeql-action/analyze@b2c19fb9a2a485599ccf4ed5d65527d94bc57226 # v2.1.11
  deploy-snapshot:
    name: Deploy SNAPSHOT Release
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop'
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.0.2
      with:
        token: ${{ github.token }}
        submodules: recursive
    # -------------------------
    # Java JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.3.0
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
        settings-path: ${{ github.workspace }}
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    # -------------------------
    # Maven Deploy
    # -------------------------
    - name: Deploy Maven Artifact SNAPSHOTs
      run: |
        mvn -s $GITHUB_WORKSPACE/settings.xml -Pgpg -Preporting -Dmaven.deploy.skip=releases deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Archive binaries
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: binary-artifacts
        path: |
          cli-core/target/*.zip
          cli-core/target/*.bz2
