on:
  push:
    branches:
    - main
    - develop
    - release-*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
    - develop
    - release-*
  workflow_dispatch:
name: Build and Test Code
jobs:
  build-artifacts:
    name: Build Java Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        token: ${{ github.token }}
        submodules: recursive
        fetch-depth: 0
    # -------------------------
    # Java Environment Setup
    # -------------------------
    - name: Set up Maven
      uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0
      with:
        maven-version: 3.9.3
    - name: Set up JDK 11 (build only)
      if: ${{ !((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop') }}
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up JDK 11 (deploy)
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop'
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Initialize CodeQL
      if: github.event_name == 'push'
      uses: github/codeql-action/init@cdf488f595d80d6e07e03d4674febd5ab45fa938
      with:
        languages: java
    # -------------------------
    # Maven Build
    # DEPLOY needs fix due to sonatype changes:
    # mvn -B -e -Pgpg -Prelease -Preporting deploy -Dmaven.deploy.skip=releases
    # -------------------------
    - name: Build and Test Code
      if: ${{ !((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop') }}
      run: |
        mvn -B -e -Prelease -Preporting install
    - name: Build, Test and DEPLOY SNAPSHOT Code
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop'
      run: |
        mvn -B -e -Prelease -Preporting install
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Perform CodeQL Analysis
      if: github.event_name == 'push'
      uses: github/codeql-action/analyze@cdf488f595d80d6e07e03d4674febd5ab45fa938
    - name: Test Website
      run: |
        # this needs to be run as a second build to ensure source is fully generated by the previous step
        mvn -B -e -Prelease -Preporting install site site:stage
